[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn gestao_empresarial.wsgi:application"
healthcheckPath = "/admin/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
PYTHON_VERSION = "3.11" 