# Generated by Django 4.2.7 on 2025-08-01 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='conta_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.contapagar', verbose_name='Conta Principal'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='eh_parcelado',
            field=models.BooleanField(default=False, verbose_name='É Parcelado'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='numero_parcelas',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de Parcelas'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='parcela_atual',
            field=models.PositiveIntegerField(default=1, verbose_name='Parcela Atual'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='valor_parcela',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Parcela'),
        ),
    ]
