# Generated by Django 4.2.7 on 2025-08-01 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
        ('contas', '0002_contapagar_conta_principal_contapagar_eh_parcelado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='contapagar',
            options={'ordering': ['data_vencimento'], 'verbose_name': 'Conta a Pagar', 'verbose_name_plural': 'Contas a Pagar'},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='despesadiaria',
            name='atualizado_em',
        ),
        migrations.AddField(
            model_name='categoria',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fornecedores.fornecedor', verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Pago'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='conta_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='contas.contapagar', verbose_name='Conta Principal'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='numero_parcelas',
            field=models.IntegerField(default=1, verbose_name='Número de Parcelas'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='parcela_atual',
            field=models.IntegerField(default=1, verbose_name='Parcela Atual'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='pendente', max_length=10, verbose_name='Status'),
        ),
    ]
