# Generated by Django 4.2.7 on 2025-08-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_alter_categoria_options_alter_contapagar_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='data_fim_recorrencia',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fim da Recorrência'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='eh_recorrente',
            field=models.BooleanField(default=False, verbose_name='É Recorrente'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='proxima_geracao',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima Geração'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='tipo_recorrencia',
            field=models.CharField(blank=True, choices=[('mensal', 'Mensal'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal')], max_length=20, null=True, verbose_name='Tipo de Recorrência'),
        ),
    ]
