# Generated by Django 4.2.7 on 2025-08-01 18:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_acesso', models.CharField(choices=[('admin', 'Administrador'), ('gerente', 'Gerente'), ('usuario', 'Usuário'), ('visualizador', 'Visualizador')], default='usuario', max_length=15, verbose_name='Nível de Acesso')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('suspenso', 'Suspenso')], default='ativo', max_length=10, verbose_name='Status')),
                ('cpf', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato XXX.XXX.XXX-XX', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('data_admissao', models.DateField(blank=True, null=True, verbose_name='Data de Admissão')),
                ('foto', models.ImageField(blank=True, upload_to='fotos_usuarios/', verbose_name='Foto')),
                ('tema_escuro', models.BooleanField(default=False, verbose_name='Tema Escuro')),
                ('notificacoes_email', models.BooleanField(default=True, verbose_name='Notificações por E-mail')),
                ('notificacoes_sistema', models.BooleanField(default=True, verbose_name='Notificações do Sistema')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True, verbose_name='Último Acesso')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuário',
            },
        ),
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('modulo', models.CharField(max_length=50, verbose_name='Módulo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Permissão',
                'verbose_name_plural': 'Permissões',
            },
        ),
        migrations.CreateModel(
            name='LogAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acesso', models.DateTimeField(auto_now_add=True, verbose_name='Data de Acesso')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('pagina_acessada', models.CharField(blank=True, max_length=200, verbose_name='Página Acessada')),
                ('acao', models.CharField(blank=True, max_length=50, verbose_name='Ação')),
                ('sucesso', models.BooleanField(default=True, verbose_name='Sucesso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Acesso',
                'verbose_name_plural': 'Logs de Acesso',
                'ordering': ['-data_acesso'],
            },
        ),
        migrations.CreateModel(
            name='GrupoPermissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('permissoes', models.ManyToManyField(to='usuarios.permissao', verbose_name='Permissões')),
            ],
            options={
                'verbose_name': 'Grupo de Permissão',
                'verbose_name_plural': 'Grupos de Permissão',
            },
        ),
        migrations.CreateModel(
            name='UsuarioPermissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concedida_em', models.DateTimeField(auto_now_add=True, verbose_name='Concedida em')),
                ('concedida_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Concedida por')),
                ('permissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.permissao', verbose_name='Permissão')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Permissão de Usuário',
                'verbose_name_plural': 'Permissões de Usuário',
                'unique_together': {('usuario', 'permissao')},
            },
        ),
    ]
