# Generated by Django 4.2.7 on 2025-06-08 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GerenciadorSenhas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('usuario_login', models.CharField(max_length=100, verbose_name='Usuário/Login')),
                ('senha_criptografada', models.BinaryField(verbose_name='Senha Criptografada')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('favorito', models.BooleanField(default=False, verbose_name='Favorito')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Senha',
                'verbose_name_plural': 'Senhas',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='ChaveCriptografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.TextField(verbose_name='Chave')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Chave de Criptografia',
                'verbose_name_plural': 'Chaves de Criptografia',
            },
        ),
    ]
