# Generated by Django 4.2.7 on 2025-08-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerenciadorsenhas',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='senhas_arquivos/', verbose_name='Arquivo'),
        ),
    ]
