# Generated by Django 4.2.7 on 2025-08-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0002_gerenciadorsenhas_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerenciadorsenhas',
            name='categoria',
            field=models.CharField(choices=[('banco', 'Banco'), ('email', 'E-mail'), ('social', 'Rede Social'), ('trabalho', 'Trabalho'), ('pessoal', 'Pessoal'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='gerenciadorsenhas',
            name='data_expiracao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Expiração'),
        ),
        migrations.AddField(
            model_name='gerenciadorsenhas',
            name='forca_senha',
            field=models.IntegerField(default=0, verbose_name='Força da Senha (0-100)'),
        ),
        migrations.AddField(
            model_name='gerenciadorsenhas',
            name='tags',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tags (separadas por vírgula)'),
        ),
        migrations.AddField(
            model_name='gerenciadorsenhas',
            name='ultima_alteracao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Alteração'),
        ),
    ]
